apiVersion: v1
kind: ConfigMap
metadata:
  name: contour-configmap
  namespace: ingress-system  # +workload:namespace:default=ingress-system:type=string
data:
  config.yaml: | # Test Comment
    someoption: myoption
    anotheroption: another
    justtesting: multistringyaml