apiVersion: apps/v1
kind: Deployment
metadata:
    name: !!var '{{ .Name }}'
spec:
    replicas: 2
    selector:
        matchLabels:
            app: webstore
    template:
        metadata:
            labels:
                app: !!var '{{ .Label }}'
        spec:
            containers:
              - name: webstore-container
                image: !!tpl my-private-repo/!!start Image !!end
                ports:
                  - containerPort: 8080